=== abbazs/OBT/json_templates/template2_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Trade",
    "definitions": {
        "Trade": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                },
                "created_on": {
                    "type": "string"
                },
                "active": {
                    "type": "boolean"
                },
                "PNL": {
                    "type": "integer"
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Position"
                    }
                }
            },
            "required": [
                "PNL",
                "active",
                "created_on",
                "id",
                "name",
                "positions",
                "user"
            ],
            "title": "Trade"
        },
        "Position": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "index": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "instrument": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "strike": {
                    "anyOf": [
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "ST": {
                    "type": "string"
                },
                "ND": {
                    "type": "string"
                },
                "ED": {
                    "type": "string"
                },
                "TT": {
                    "type": "string"
                },
                "OPR": {
                    "type": "integer"
                },
                "CPR": {
                    "type": "integer"
                }
            },
            "required": [
                "ED",
                "OPR",
                "ST",
                "TT",
                "instrument",
                "strike",
                "symbol",
                "type"
            ],
            "title": "Position"
        }
    }
}

=== abbazs/OBT/json_templates/template2.json
{
    "name": "User given name",
    "id": 0,
    "user": "userid",
    "created_on": "date",
    "active": true,
    "PNL": 0,
    "positions": [
        {
            "index": 0,
            "symbol": "NIFTY",
            "instrument": "options",
            "type": "call",
            "strike": 12100,
            "ST": "start date",
            "ND": "end date",
            "ED": "expiry date",
            "TT": "SELL",
            "OPR": 203,
            "CPR": 150
        },
        {
            "index": 1,
            "symbol": "NIFTY",
            "instrument": "options",
            "type": "put",
            "strike": 12100,
            "ST": "start date",
            "ND": "end date",
            "ED": "expiry date",
            "TT": "SELL",
            "OPR": 203,
            "CPR": 150
        },
        {
            "index": 2,
            "symbol": "NIFTY",
            "instrument": "options",
            "type": "future",
            "strike": null,
            "ST": "start date",
            "ND": "end date",
            "ED": "expiry date",
            "TT": "BUY",
            "OPR": 203,
            "CPR": 150
        }
    ]
}
